name: CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Swift
      uses: fwal/setup-swift@v1.5.0
    - name: Run tests
      run: swift build
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run SwiftLint --strict
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
